name: 'docker-image'
on:
  push:
    branches:
      - master
    paths:
      - 'Dockers/go-builder/**'
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Build and push image
        run: |
          docker build -t ashwatth:${VERSION} Dockers/go-builder
