name: 'docker-image'
on:
  push:
    branches:
      - master
    paths:
      - 'Dockers/go-builder/**'
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v2

      - name: Build and push image
        run: |
          docker build -t ashwatth:${GITHUB_REF} Dockers/go-builder
